results_dir: results
episode_budget: 100_000
eval_check_interval: 100
save_interval: 100

SelfPlay:
  self_play_period: 1000  # epochs
  opponent: weak  # weak, strong, self_play
  Env:
    keep_mode: true
    mode: NORMAL
    verbose: false
  WarmupSchedule:
    n_episodes_weak: 200
    n_episodes_strong: 800

SAC:
  learning_rate: 0.0003
  buffer_size: 1_000_000
  learning_starts: 100
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
  action_noise: null
  optimize_memory_usage: false
  ent_coef: "auto"
  target_update_interval: 1
  target_entropy: "auto"
  use_sde: false
  sde_sample_freq: -1
  use_sde_at_warmup: false
  stats_window_size: 100