results_dir: results
episode_budget: 100_000
eval_check_interval: 100
save_interval: 100  


SelfPlay:
  self_play_period: 1000  # epochs
  opponent: weak  # weak, strong, self_play
  Env:
    keep_mode: true
    mode: NORMAL
    verbose: false
  WarmupSchedule:
    n_episodes_weak: 200
    n_episodes_strong: 800


Dyna:
  batch_size: 256
  buffer_limit: 50_000
  start_buffer_size: 2000
  target_entropy: null
  init_alpha: 0.0001
  lr_alpha: 0.001
  gamma: 0.99
  tau: 0.01
  simulation_updates: 2